/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Capsule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Capsule#isTop <em>Top</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Capsule#getName <em>Name</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Capsule#getCppProps <em>Cpp Props</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Capsule#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Capsule#getOperations <em>Operations</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Capsule#getParts <em>Parts</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Capsule#getPorts <em>Ports</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Capsule#getConnectors <em>Connectors</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Capsule#getStateMachine <em>State Machine</em>}</li>
 * </ul>
 *
 * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getCapsule()
 * @model
 * @generated
 */
public interface Capsule extends EObject
{
  /**
   * Returns the value of the '<em><b>Top</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Top</em>' attribute.
   * @see #setTop(boolean)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getCapsule_Top()
   * @model
   * @generated
   */
  boolean isTop();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Capsule#isTop <em>Top</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Top</em>' attribute.
   * @see #isTop()
   * @generated
   */
  void setTop(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getCapsule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Capsule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Cpp Props</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cpp Props</em>' containment reference.
   * @see #setCppProps(ClassCppProps)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getCapsule_CppProps()
   * @model containment="true"
   * @generated
   */
  ClassCppProps getCppProps();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Capsule#getCppProps <em>Cpp Props</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cpp Props</em>' containment reference.
   * @see #getCppProps()
   * @generated
   */
  void setCppProps(ClassCppProps value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getCapsule_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Operation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getCapsule_Operations()
   * @model containment="true"
   * @generated
   */
  EList<Operation> getOperations();

  /**
   * Returns the value of the '<em><b>Parts</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Part}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parts</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getCapsule_Parts()
   * @model containment="true"
   * @generated
   */
  EList<Part> getParts();

  /**
   * Returns the value of the '<em><b>Ports</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Port}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ports</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getCapsule_Ports()
   * @model containment="true"
   * @generated
   */
  EList<Port> getPorts();

  /**
   * Returns the value of the '<em><b>Connectors</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Connector}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connectors</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getCapsule_Connectors()
   * @model containment="true"
   * @generated
   */
  EList<Connector> getConnectors();

  /**
   * Returns the value of the '<em><b>State Machine</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State Machine</em>' containment reference.
   * @see #setStateMachine(StateMachine)
   * @see RtPackage#getCapsule_StateMachine()
   * @model containment="true"
   * @generated
   */
  StateMachine getStateMachine();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Capsule#getStateMachine <em>State Machine</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State Machine</em>' containment reference.
   * @see #getStateMachine()
   * @generated
   */
  void setStateMachine(StateMachine value);

} // Capsule
