/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choice Point</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getChoicePoint()
 * @model
 * @generated
 */
public interface ChoicePoint extends PseudoState
{
} // ChoicePoint
