/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Class#getCppProps <em>Cpp Props</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Class#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Class#getOperations <em>Operations</em>}</li>
 * </ul>
 *
 * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getClass_()
 * @model
 * @generated
 */
public interface Class extends UserType
{
  /**
   * Returns the value of the '<em><b>Cpp Props</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cpp Props</em>' containment reference.
   * @see #setCppProps(ClassCppProps)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getClass_CppProps()
   * @model containment="true"
   * @generated
   */
  ClassCppProps getCppProps();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Class#getCppProps <em>Cpp Props</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cpp Props</em>' containment reference.
   * @see #getCppProps()
   * @generated
   */
  void setCppProps(ClassCppProps value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getClass_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Operation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getClass_Operations()
   * @model containment="true"
   * @generated
   */
  EList<Operation> getOperations();

} // Class
