/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Composite State Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.CompositeStateBody#getSubstates <em>Substates</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.CompositeStateBody#getTransitions <em>Transitions</em>}</li>
 * </ul>
 *
 * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getCompositeStateBody()
 * @model
 * @generated
 */
public interface CompositeStateBody extends StateCommonFragment
{
  /**
   * Returns the value of the '<em><b>Substates</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.State}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Substates</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getCompositeStateBody_Substates()
   * @model containment="true"
   * @generated
   */
  EList<State> getSubstates();

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Transition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getCompositeStateBody_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<Transition> getTransitions();

} // CompositeStateBody
