/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connector</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Connector#getPart1 <em>Part1</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Connector#getPort1 <em>Port1</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Connector#getPart2 <em>Part2</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Connector#getPort2 <em>Port2</em>}</li>
 * </ul>
 *
 * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getConnector()
 * @model
 * @generated
 */
public interface Connector extends EObject
{
  /**
   * Returns the value of the '<em><b>Part1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Part1</em>' reference.
   * @see #setPart1(ca.jahed.rtpoet.dsl.rt.Part)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getConnector_Part1()
   * @model
   * @generated
   */
  ca.jahed.rtpoet.dsl.rt.Part getPart1();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Connector#getPart1 <em>Part1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Part1</em>' reference.
   * @see #getPart1()
   * @generated
   */
  void setPart1(ca.jahed.rtpoet.dsl.rt.Part value);

  /**
   * Returns the value of the '<em><b>Port1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port1</em>' reference.
   * @see #setPort1(ca.jahed.rtpoet.dsl.rt.Port)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getConnector_Port1()
   * @model
   * @generated
   */
  ca.jahed.rtpoet.dsl.rt.Port getPort1();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Connector#getPort1 <em>Port1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port1</em>' reference.
   * @see #getPort1()
   * @generated
   */
  void setPort1(ca.jahed.rtpoet.dsl.rt.Port value);

  /**
   * Returns the value of the '<em><b>Part2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Part2</em>' reference.
   * @see #setPart2(ca.jahed.rtpoet.dsl.rt.Part)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getConnector_Part2()
   * @model
   * @generated
   */
  ca.jahed.rtpoet.dsl.rt.Part getPart2();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Connector#getPart2 <em>Part2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Part2</em>' reference.
   * @see #getPart2()
   * @generated
   */
  void setPart2(Part value);

  /**
   * Returns the value of the '<em><b>Port2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port2</em>' reference.
   * @see #setPort2(ca.jahed.rtpoet.dsl.rt.Port)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getConnector_Port2()
   * @model
   * @generated
   */
  ca.jahed.rtpoet.dsl.rt.Port getPort2();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Connector#getPort2 <em>Port2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port2</em>' reference.
   * @see #getPort2()
   * @generated
   */
  void setPort2(Port value);

} // Connector
