/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entry Point</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getEntryPoint()
 * @model
 * @generated
 */
public interface EntryPoint extends PseudoState
{
} // EntryPoint
