/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal Real</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.LiteralReal#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getLiteralReal()
 * @model
 * @generated
 */
public interface LiteralReal extends Literal
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getLiteralReal_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.LiteralReal#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // LiteralReal
