/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Package</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Package#getName <em>Name</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Package#getCapsules <em>Capsules</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Package#getClasses <em>Classes</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Package#getEnumerations <em>Enumerations</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Package#getArtifacts <em>Artifacts</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Package#getProtocols <em>Protocols</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Package#getPackages <em>Packages</em>}</li>
 * </ul>
 *
 * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPackage()
 * @model
 * @generated
 */
public interface Package extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPackage_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Package#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Capsules</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Capsule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capsules</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPackage_Capsules()
   * @model containment="true"
   * @generated
   */
  EList<Capsule> getCapsules();

  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Class}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPackage_Classes()
   * @model containment="true"
   * @generated
   */
  EList<ca.jahed.rtpoet.dsl.rt.Class> getClasses();

  /**
   * Returns the value of the '<em><b>Enumerations</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Enumeration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumerations</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPackage_Enumerations()
   * @model containment="true"
   * @generated
   */
  EList<Enumeration> getEnumerations();

  /**
   * Returns the value of the '<em><b>Artifacts</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Artifact}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Artifacts</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPackage_Artifacts()
   * @model containment="true"
   * @generated
   */
  EList<Artifact> getArtifacts();

  /**
   * Returns the value of the '<em><b>Protocols</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Protocol}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Protocols</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPackage_Protocols()
   * @model containment="true"
   * @generated
   */
  EList<Protocol> getProtocols();

  /**
   * Returns the value of the '<em><b>Packages</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Package}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Packages</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPackage_Packages()
   * @model containment="true"
   * @generated
   */
  EList<Package> getPackages();

} // Package
