/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Port</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Port#getKind <em>Kind</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Port#getRegistration <em>Registration</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Port#getName <em>Name</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Port#isConjugate <em>Conjugate</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Port#getType <em>Type</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Port#getUpperBound <em>Upper Bound</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Port#getRegistrationOverride <em>Registration Override</em>}</li>
 * </ul>
 *
 * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPort()
 * @model
 * @generated
 */
public interface Port extends EObject
{
  /**
   * Returns the value of the '<em><b>Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' attribute.
   * @see #setKind(String)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPort_Kind()
   * @model
   * @generated
   */
  String getKind();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Port#getKind <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' attribute.
   * @see #getKind()
   * @generated
   */
  void setKind(String value);

  /**
   * Returns the value of the '<em><b>Registration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Registration</em>' attribute.
   * @see #setRegistration(String)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPort_Registration()
   * @model
   * @generated
   */
  String getRegistration();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Port#getRegistration <em>Registration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Registration</em>' attribute.
   * @see #getRegistration()
   * @generated
   */
  void setRegistration(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPort_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Port#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Conjugate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conjugate</em>' attribute.
   * @see #setConjugate(boolean)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPort_Conjugate()
   * @model
   * @generated
   */
  boolean isConjugate();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Port#isConjugate <em>Conjugate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conjugate</em>' attribute.
   * @see #isConjugate()
   * @generated
   */
  void setConjugate(boolean value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Protocol)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPort_Type()
   * @model
   * @generated
   */
  Protocol getType();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Port#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Protocol value);

  /**
   * Returns the value of the '<em><b>Upper Bound</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Upper Bound</em>' containment reference.
   * @see #setUpperBound(LiteralInteger)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPort_UpperBound()
   * @model containment="true"
   * @generated
   */
  LiteralInteger getUpperBound();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Port#getUpperBound <em>Upper Bound</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Upper Bound</em>' containment reference.
   * @see #getUpperBound()
   * @generated
   */
  void setUpperBound(LiteralInteger value);

  /**
   * Returns the value of the '<em><b>Registration Override</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Registration Override</em>' attribute.
   * @see #setRegistrationOverride(String)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getPort_RegistrationOverride()
   * @model
   * @generated
   */
  String getRegistrationOverride();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Port#getRegistrationOverride <em>Registration Override</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Registration Override</em>' attribute.
   * @see #getRegistrationOverride()
   * @generated
   */
  void setRegistrationOverride(String value);

} // Port
