/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getState()
 * @model
 * @generated
 */
public interface State extends EObject
{
} // State
