/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Transition#getSource <em>Source</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Transition#getTarget <em>Target</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Transition#getTriggers <em>Triggers</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Transition#getGuard <em>Guard</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Transition#getActionChain <em>Action Chain</em>}</li>
 * </ul>
 *
 * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getTransition()
 * @model
 * @generated
 */
public interface Transition extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(ca.jahed.rtpoet.dsl.rt.State)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getTransition_Source()
   * @model
   * @generated
   */
  ca.jahed.rtpoet.dsl.rt.State getSource();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Transition#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(ca.jahed.rtpoet.dsl.rt.State value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(ca.jahed.rtpoet.dsl.rt.State)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getTransition_Target()
   * @model
   * @generated
   */
  ca.jahed.rtpoet.dsl.rt.State getTarget();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Transition#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(State value);

  /**
   * Returns the value of the '<em><b>Triggers</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Trigger}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Triggers</em>' containment reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getTransition_Triggers()
   * @model containment="true"
   * @generated
   */
  EList<Trigger> getTriggers();

  /**
   * Returns the value of the '<em><b>Guard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guard</em>' containment reference.
   * @see #setGuard(TransitionGuard)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getTransition_Guard()
   * @model containment="true"
   * @generated
   */
  TransitionGuard getGuard();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Transition#getGuard <em>Guard</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Guard</em>' containment reference.
   * @see #getGuard()
   * @generated
   */
  void setGuard(TransitionGuard value);

  /**
   * Returns the value of the '<em><b>Action Chain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Chain</em>' containment reference.
   * @see #setActionChain(TransitionAction)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getTransition_ActionChain()
   * @model containment="true"
   * @generated
   */
  TransitionAction getActionChain();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Transition#getActionChain <em>Action Chain</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action Chain</em>' containment reference.
   * @see #getActionChain()
   * @generated
   */
  void setActionChain(TransitionAction value);

} // Transition
