/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trigger</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Trigger#getPorts <em>Ports</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Trigger#getSignal <em>Signal</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Trigger#isAny <em>Any</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Trigger#isRtBound <em>Rt Bound</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.Trigger#isRtUnbound <em>Rt Unbound</em>}</li>
 * </ul>
 *
 * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getTrigger()
 * @model
 * @generated
 */
public interface Trigger extends EObject
{
  /**
   * Returns the value of the '<em><b>Ports</b></em>' reference list.
   * The list contents are of type {@link ca.jahed.rtpoet.dsl.rt.Port}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ports</em>' reference list.
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getTrigger_Ports()
   * @model
   * @generated
   */
  EList<Port> getPorts();

  /**
   * Returns the value of the '<em><b>Signal</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signal</em>' reference.
   * @see #setSignal(ca.jahed.rtpoet.dsl.rt.Signal)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getTrigger_Signal()
   * @model
   * @generated
   */
  ca.jahed.rtpoet.dsl.rt.Signal getSignal();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Trigger#getSignal <em>Signal</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Signal</em>' reference.
   * @see #getSignal()
   * @generated
   */
  void setSignal(Signal value);

  /**
   * Returns the value of the '<em><b>Any</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Any</em>' attribute.
   * @see #setAny(boolean)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getTrigger_Any()
   * @model
   * @generated
   */
  boolean isAny();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Trigger#isAny <em>Any</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Any</em>' attribute.
   * @see #isAny()
   * @generated
   */
  void setAny(boolean value);

  /**
   * Returns the value of the '<em><b>Rt Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rt Bound</em>' attribute.
   * @see #setRtBound(boolean)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getTrigger_RtBound()
   * @model
   * @generated
   */
  boolean isRtBound();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Trigger#isRtBound <em>Rt Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rt Bound</em>' attribute.
   * @see #isRtBound()
   * @generated
   */
  void setRtBound(boolean value);

  /**
   * Returns the value of the '<em><b>Rt Unbound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rt Unbound</em>' attribute.
   * @see #setRtUnbound(boolean)
   * @see ca.jahed.rtpoet.dsl.rt.RtPackage#getTrigger_RtUnbound()
   * @model
   * @generated
   */
  boolean isRtUnbound();

  /**
   * Sets the value of the '{@link ca.jahed.rtpoet.dsl.rt.Trigger#isRtUnbound <em>Rt Unbound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rt Unbound</em>' attribute.
   * @see #isRtUnbound()
   * @generated
   */
  void setRtUnbound(boolean value);

} // Trigger
