/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt.impl;

import ca.jahed.rtpoet.dsl.rt.ChoicePoint;
import ca.jahed.rtpoet.dsl.rt.RtPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Choice Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ChoicePointImpl extends PseudoStateImpl implements ChoicePoint
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ChoicePointImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RtPackage.Literals.CHOICE_POINT;
  }

} //ChoicePointImpl
