/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt.impl;

import ca.jahed.rtpoet.dsl.rt.DeepHistory;
import ca.jahed.rtpoet.dsl.rt.RtPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Deep History</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DeepHistoryImpl extends PseudoStateImpl implements DeepHistory
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeepHistoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RtPackage.Literals.DEEP_HISTORY;
  }

} //DeepHistoryImpl
