/**
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.rt.impl;

import ca.jahed.rtpoet.dsl.rt.Artifact;
import ca.jahed.rtpoet.dsl.rt.Capsule;
import ca.jahed.rtpoet.dsl.rt.Enumeration;
import ca.jahed.rtpoet.dsl.rt.Import;
import ca.jahed.rtpoet.dsl.rt.Model;
import ca.jahed.rtpoet.dsl.rt.Protocol;
import ca.jahed.rtpoet.dsl.rt.RtPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.impl.ModelImpl#getName <em>Name</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.impl.ModelImpl#getImports <em>Imports</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.impl.ModelImpl#getCapsules <em>Capsules</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.impl.ModelImpl#getClasses <em>Classes</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.impl.ModelImpl#getEnumerations <em>Enumerations</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.impl.ModelImpl#getArtifacts <em>Artifacts</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.impl.ModelImpl#getProtocols <em>Protocols</em>}</li>
 *   <li>{@link ca.jahed.rtpoet.dsl.rt.impl.ModelImpl#getPackages <em>Packages</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getImports() <em>Imports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports()
   * @generated
   * @ordered
   */
  protected EList<Import> imports;

  /**
   * The cached value of the '{@link #getCapsules() <em>Capsules</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapsules()
   * @generated
   * @ordered
   */
  protected EList<Capsule> capsules;

  /**
   * The cached value of the '{@link #getClasses() <em>Classes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClasses()
   * @generated
   * @ordered
   */
  protected EList<ca.jahed.rtpoet.dsl.rt.Class> classes;

  /**
   * The cached value of the '{@link #getEnumerations() <em>Enumerations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumerations()
   * @generated
   * @ordered
   */
  protected EList<Enumeration> enumerations;

  /**
   * The cached value of the '{@link #getArtifacts() <em>Artifacts</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArtifacts()
   * @generated
   * @ordered
   */
  protected EList<Artifact> artifacts;

  /**
   * The cached value of the '{@link #getProtocols() <em>Protocols</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProtocols()
   * @generated
   * @ordered
   */
  protected EList<Protocol> protocols;

  /**
   * The cached value of the '{@link #getPackages() <em>Packages</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPackages()
   * @generated
   * @ordered
   */
  protected EList<ca.jahed.rtpoet.dsl.rt.Package> packages;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RtPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RtPackage.MODEL__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Import> getImports()
  {
    if (imports == null)
    {
      imports = new EObjectContainmentEList<Import>(Import.class, this, RtPackage.MODEL__IMPORTS);
    }
    return imports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Capsule> getCapsules()
  {
    if (capsules == null)
    {
      capsules = new EObjectContainmentEList<Capsule>(Capsule.class, this, RtPackage.MODEL__CAPSULES);
    }
    return capsules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ca.jahed.rtpoet.dsl.rt.Class> getClasses()
  {
    if (classes == null)
    {
      classes = new EObjectContainmentEList<ca.jahed.rtpoet.dsl.rt.Class>(ca.jahed.rtpoet.dsl.rt.Class.class, this, RtPackage.MODEL__CLASSES);
    }
    return classes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Enumeration> getEnumerations()
  {
    if (enumerations == null)
    {
      enumerations = new EObjectContainmentEList<Enumeration>(Enumeration.class, this, RtPackage.MODEL__ENUMERATIONS);
    }
    return enumerations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Artifact> getArtifacts()
  {
    if (artifacts == null)
    {
      artifacts = new EObjectContainmentEList<Artifact>(Artifact.class, this, RtPackage.MODEL__ARTIFACTS);
    }
    return artifacts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Protocol> getProtocols()
  {
    if (protocols == null)
    {
      protocols = new EObjectContainmentEList<Protocol>(Protocol.class, this, RtPackage.MODEL__PROTOCOLS);
    }
    return protocols;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ca.jahed.rtpoet.dsl.rt.Package> getPackages()
  {
    if (packages == null)
    {
      packages = new EObjectContainmentEList<ca.jahed.rtpoet.dsl.rt.Package>(ca.jahed.rtpoet.dsl.rt.Package.class, this, RtPackage.MODEL__PACKAGES);
    }
    return packages;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RtPackage.MODEL__IMPORTS:
        return ((InternalEList<?>)getImports()).basicRemove(otherEnd, msgs);
      case RtPackage.MODEL__CAPSULES:
        return ((InternalEList<?>)getCapsules()).basicRemove(otherEnd, msgs);
      case RtPackage.MODEL__CLASSES:
        return ((InternalEList<?>)getClasses()).basicRemove(otherEnd, msgs);
      case RtPackage.MODEL__ENUMERATIONS:
        return ((InternalEList<?>)getEnumerations()).basicRemove(otherEnd, msgs);
      case RtPackage.MODEL__ARTIFACTS:
        return ((InternalEList<?>)getArtifacts()).basicRemove(otherEnd, msgs);
      case RtPackage.MODEL__PROTOCOLS:
        return ((InternalEList<?>)getProtocols()).basicRemove(otherEnd, msgs);
      case RtPackage.MODEL__PACKAGES:
        return ((InternalEList<?>)getPackages()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RtPackage.MODEL__NAME:
        return getName();
      case RtPackage.MODEL__IMPORTS:
        return getImports();
      case RtPackage.MODEL__CAPSULES:
        return getCapsules();
      case RtPackage.MODEL__CLASSES:
        return getClasses();
      case RtPackage.MODEL__ENUMERATIONS:
        return getEnumerations();
      case RtPackage.MODEL__ARTIFACTS:
        return getArtifacts();
      case RtPackage.MODEL__PROTOCOLS:
        return getProtocols();
      case RtPackage.MODEL__PACKAGES:
        return getPackages();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RtPackage.MODEL__NAME:
        setName((String)newValue);
        return;
      case RtPackage.MODEL__IMPORTS:
        getImports().clear();
        getImports().addAll((Collection<? extends Import>)newValue);
        return;
      case RtPackage.MODEL__CAPSULES:
        getCapsules().clear();
        getCapsules().addAll((Collection<? extends Capsule>)newValue);
        return;
      case RtPackage.MODEL__CLASSES:
        getClasses().clear();
        getClasses().addAll((Collection<? extends ca.jahed.rtpoet.dsl.rt.Class>)newValue);
        return;
      case RtPackage.MODEL__ENUMERATIONS:
        getEnumerations().clear();
        getEnumerations().addAll((Collection<? extends Enumeration>)newValue);
        return;
      case RtPackage.MODEL__ARTIFACTS:
        getArtifacts().clear();
        getArtifacts().addAll((Collection<? extends Artifact>)newValue);
        return;
      case RtPackage.MODEL__PROTOCOLS:
        getProtocols().clear();
        getProtocols().addAll((Collection<? extends Protocol>)newValue);
        return;
      case RtPackage.MODEL__PACKAGES:
        getPackages().clear();
        getPackages().addAll((Collection<? extends ca.jahed.rtpoet.dsl.rt.Package>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RtPackage.MODEL__NAME:
        setName(NAME_EDEFAULT);
        return;
      case RtPackage.MODEL__IMPORTS:
        getImports().clear();
        return;
      case RtPackage.MODEL__CAPSULES:
        getCapsules().clear();
        return;
      case RtPackage.MODEL__CLASSES:
        getClasses().clear();
        return;
      case RtPackage.MODEL__ENUMERATIONS:
        getEnumerations().clear();
        return;
      case RtPackage.MODEL__ARTIFACTS:
        getArtifacts().clear();
        return;
      case RtPackage.MODEL__PROTOCOLS:
        getProtocols().clear();
        return;
      case RtPackage.MODEL__PACKAGES:
        getPackages().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RtPackage.MODEL__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case RtPackage.MODEL__IMPORTS:
        return imports != null && !imports.isEmpty();
      case RtPackage.MODEL__CAPSULES:
        return capsules != null && !capsules.isEmpty();
      case RtPackage.MODEL__CLASSES:
        return classes != null && !classes.isEmpty();
      case RtPackage.MODEL__ENUMERATIONS:
        return enumerations != null && !enumerations.isEmpty();
      case RtPackage.MODEL__ARTIFACTS:
        return artifacts != null && !artifacts.isEmpty();
      case RtPackage.MODEL__PROTOCOLS:
        return protocols != null && !protocols.isEmpty();
      case RtPackage.MODEL__PACKAGES:
        return packages != null && !packages.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ModelImpl
